version: "3"

services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
    networks:
      - sonar-network
    environment:
      - SONAR_FORCEAUTHENTICATION=false

networks:
  sonar-network: